apiVersion: v1
kind: Secret
metadata:
  name: battlearena-secret
  namespace: battlearena
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret123
  DATABASE_URL: postgresql://admin:secret123@postgres-service:5432/battlearena
